#!/bin/bash
#
# Script: gw
# Descript: Change user work directory
# Version: 4.0.1
# Package Version: 4.0.13
# Date: 2016.06.23
# Author: Bob Chang
# Tested: CentOS 6.x, Cygwin NT 6.1
# Note:
#

script_name=gw
script_full_name=gw
this_file=/usr/local/bin/$script_full_name
sw_file=/usr/local/bin/sw

get_version() {
        local version=`grep '^# Version:' $this_file|cut -d ' ' -f 3`
        echo $version
}

version=`get_version`

tag_folder=/tmp

#
show_usage() {
        cat<<here
$script_full_name, v$version

Change work directory to target tag

Usage: $script_full_name [<tag>|-c|-d <tag>|-h|-V]

tag	    composed of [a-zA-Z0-9_-]

Options
  N/A	    show tags info
  tag	    go to tag's directory
  -c        clean (delete) all tags in path list.
  -d tag    delete tag in path list.
  -h        show this help
  -V        show version

EXAMPLE
  $script_full_name
  $script_full_name a
  $script_full_name -d b
  $script_full_name -c

here
}

go_to() {
	local tag_name=$1

	#naming rule, only [a-zA-Z0-9_-]
	local name_ok=`perl -w -e '$name=shift;if($name =~ /^[a-zA-Z0-9_-]+$/){print 0;}else{print 1}' $tag_name 2>/dev/null`

	if [ $name_ok -eq 1 ];then	#no ok
		:;	#do nothing
	fi

	local list=`$sw_file -gf`

	local path=`grep ^$tag_name, $list|cut -d ',' -f 2`

	if [ ! -z $path ];then	#found
		#echo $path
		cd $path
		pwd
	fi
}

show_version() {
	echo $version
}

## Main ##
if [ $# -eq 0 ];then
	$sw_file
else
	case $1 in
		-c) source $sw_file -c
		;;
		-d) source $sw_file -d $2
		;;
		-h) show_usage
		;;
		-V) show_version
		;;
		*) go_to $1
		;;
	esac
fi

### End of script ##
