#!/bin/bash
#
# Script: gw
# Descript: Change user work directory
# Version: 4.1.0
# Package Version: 4.1.x
# Date: 2017.10.31
# Update:
#	4.0.3	1. Fix tag_folder value from /tmp to ~.
#	4.1.0	1. Refactor script.
# Author: Bob Chang
# Tested: CentOS 6.x, Cygwin NT 6.1
# Note:
#	1. No duplicated function from sw. Because both functions are sourced and will influance to each other.
#	2. Functions used from sw:
#		get_script_version
#

script_name=gw
script_full_name=gw
this_file=/usr/local/bin/$script_full_name
sw_file=/usr/local/bin/sw

tag_folder=~

#
show_usage() {
	local version=`get_script_version`
	local pkg_version=`get_pkg_version`

        cat<<here
$script_full_name, v$gw_version
g2w package, $pkg_version

Change work directory to tagged path.

Usage: $script_full_name [<tag>|-c|-d <tag>|-h|-V]

tag	    composed of [a-zA-Z0-9_-]

Options
  N/A	    show tags info
  tag	    go to tagged path
  -c        clean (delete) all tags in path list.
  -d tag    delete tag in path list.
  -h        show this help
  -V        show version

EXAMPLE
  $script_full_name
  $script_full_name work_folder
  $script_full_name -d work_folder
  $script_full_name -c

here
}

#
# Function: go_to
# Description:
#
go_to() {
	local tag_name=$1

	#naming rule, only [a-zA-Z0-9_-]
	local name_ok=`perl -w -e '$name=shift;if($name =~ /^[a-zA-Z0-9_-]+$/){print 0;}else{print 1}' $tag_name 2>/dev/null`

	if [ $name_ok -eq 1 ];then	#no ok
		:;	#do nothing
	fi

	local list=`$sw_file -gf`

	local path=`grep ^$tag_name, $list|cut -d ',' -f 2`

	if [ ! -z "$path" ];then	#found
		#echo $path
		cd "$path"
		pwd
	fi
}

## Main ##
if [ $# -eq 0 ];then
	$sw_file
else
	case $1 in
		-c) source $sw_file -c
		;;
		-d) source $sw_file -d $2
		;;
		-h) show_usage
		;;
		-V) show_version
		;;
		*) go_to $1
		;;
	esac
fi

### End of script ##
