#!/bin/bash
#
# Script: install
# Description: install script for g2w
# Version: 4.0.7
# Date: 2016.08.01
#

bin_folder=/usr/local/bin
login_shell_folder=/etc/profile.d

set_alias_linux() {
	local login_script=g2w.sh

	if [ -f $login_script ];then
		echo -n "copy $login_script to $login_shell_folder ... "
		cp $login_script $login_shell_folder

		if [ $? -eq 0 ];then
			echo ok
		else
			echo error
		fi
	else
		echo "can't find $login_script"
	fi
}

set_alias_cygwin() {
	local login_script=g2w.sh

	if [ -f $login_script ];then
		echo -n "copy $login_script to $login_shell_folder ... "
		cp $login_script $login_shell_folder

		if [ $? -eq 0 ];then
			echo ok
		else
			echo error
		fi
	else
		echo "can't find $login_script"
	fi
}

set_alias() {
	local os=`uname -o`

	case $os in
		"Cygwin") set_alias_cygwin
		;;
		"GUN/Linux") set_alias_linux
		;;
		*) echo "Sorry, we don't support your system now."
		   exit 0
		;;
	esac
}	

show_messages() {
	cat <<here

Please re-login the terminal to affect the functions.
here

}

#
main() {
echo -n "check source (not finish yet) .... "
echo ok

#
echo -n "copy gw to $bin_folder .... "
cp -f gw $bin_folder

if [ $? -eq 0 ];then
	echo ok
else
	echo error
fi

#
echo -n copy sw to $bin_folder ....
cp -f sw $bin_folder

if [ $? -eq 0 ];then
	echo ok
else
	echo error
fi

	# set alias
	set_alias

	# show messasges
	show_messages

}

# main #
main

## End of Script ##
