win10,/cygdrive/f/l3/lab/windows10
restful,/cygdrive/f/l3/lab/RESTful
git_sunbird,/cygdrive/d/git_bare/sunbird
lab_git,/cygdrive/f/l3/lab/Git
bobchang,/cygdrive/c/Users/bobchang
downloads,/cygdrive/c/Users/bobchang/Downloads
jsonpath,/cygdrive/f/l3/lab/JSONPath
postg,/cygdrive/f/l3/lab/Postgresql
dctdb,/cygdrive/d/work/lab/002-dcTrack/007-Database
cnt65,/cygdrive/f/l3/lab/CentOS_65
personal,/cygdrive/f/l3/personal
vim,/cygdrive/f/l3/lab/VI_VIM
localbin,/cygdrive/d/local_bin
cygwin,/cygdrive/f/l3/lab/Cygwin
g2w,/cygdrive/d/tools/g2w/work
lab,/cygdrive/f/l3/lab
temp,/cygdrive/d/temp
massdown,/cygdrive/d/tools/massdown/work
d,/cygdrive/d
downfiles,/cygdrive/d/tools/downfiles
y,/cygdrive/y
swap,/cygdrive/f/swap
page_1,/cygdrive/c/Users/bobchang/Downloads/girls.ucrazy.ru/index_folder/page_1
english,/cygdrive/f/l3/personal/english_study
newpj,/cygdrive/d/tools/newpj/work
lfunc,/cygdrive/d/tools/lfunc/work
im,/cygdrive/f/l3/lab/ImageMagick
tap,/cygdrive/f/l3/lab/Network/tap
zmp2,/cygdrive/f/girls.ucrazy.ru/index_folder
mydoc,/cygdrive/f/l2/my_doc
rbac,/cygdrive/d/work/lab/002-dcTrack/007-Database/RBAC
delete,/cygdrive/d/delete
bkimport,/cygdrive/d/work/lab/002-dcTrack/038-bulk_import_test_templates
zephyr,/cygdrive/d/work/lab/009-Zephyr/import_tool/import_via_xls
zmp,/cygdrive/f/l3/git_bare/outsourcing.git
ssh,/home/bobchang/.ssh
sunbird,/cygdrive/d/work
perl,/cygdrive/f/l3/lab/perl
chrome,/cygdrive/f/l3/lab/Chrome
wallpaper,/cygdrive/d/wallpaper
tools,/cygdrive/d/tools
nodejs,/cygdrive/f/l3/lab/nodejs
sunbird_lab,/cygdrive/d/work/lab/002-dcTrack
wallpaper_temp,/cygdrive/y/photo_temp/wallpapers/temp4
Perl,/cygdrive/f/l2/my_doc/Perl/basic
dcim,/cygdrive/d/work/product/DCIM
upgrade,/cygdrive/d/work/lab/002-dcTrack/046-upgrade_bundle
c,/cygdrive/c
pictures,/cygdrive/c/Users/bobchang/Pictures
network,/cygdrive/d/work/Sunbird/network
user_list,/cygdrive/d/work/20161223-Manage_User_Configurable_Lists
user_list_lab,/cygdrive/d/work/20161223-Manage_User_Configurable_Lists/049-Manage_User_Configurable_List
tmp,/cygdrive/f/l3/lab/VMWare/ESXi5_5/add_hard_disk_to_host
facility,/cygdrive/d/work/Sunbird/facility
dct530,/cygdrive/d/work/product/DCIM/iso/dcTrack/5.3.0
testlic,/cygdrive/d/work/product/DCIM/iso/test_lic
Sunbird,/cygdrive/d/work/Sunbird
documents,/cygdrive/c/Users/bobchang/Documents
Javascript,/cygdrive/f/l2/my_doc/Javascript
Angular,/cygdrive/f/l2/my_doc/AngularJS
Wireless,/cygdrive/f/l2/my_doc/Wireless
user_list_jira,/cygdrive/d/work/JIRA/US/Manage_User_Configurable_Lists
f,/cygdrive/f
vmware,/cygdrive/f/l3/lab/VMWare
work,/cygdrive/f/l3/lab/Windows10/shortcut_keys
photo_tmp,/cygdrive/y/photo_temp/temp003-venus
diary,/cygdrive/f/l3/personal/diary
soapui,/cygdrive/d/work/lab/013-SoapUI/test-002
